name: ArmorSetBonus
version: 1.0
main: hkr.ArmorSetBonusMain
api-version: 1.13
author: hallis21
commands:
   armor-reload:
      description: Reloads the armor-set config file
      usage: /armor-reload
      permission: armorsetbonus.reload

permissions:
   armorsetbonus.reload:
      description: Allows a player to reload the config file
      default: true
   armorsetsonus.receive:
      description: Allows a player to receive armor set bonuses
      default: true
